openapi: 3.0.2
info:
  title: Items API
  description: This is an barebones API written by plainrandom as a means to learn and to serve as a skeleton for future API projects.
  version: 0.0.1

servers:
  # - url: http://localhost:5050/
  - url: https://api.plainrandom.com/
    description: Main demo server.

components:
  schemas:
    item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          example: thing1
        description:
          type: string
          example: This this a thing 

paths:
  /items:
    get:
      tags: 
        - Items Object
      summary: Returns a list of items.
      description: Returns a list of all Items currently in the database.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"

    post:
      tags: 
        - Items Object
      summary: Creates an item
      description: Sends a json object to the server and returns with a new entry with new UUID.
      consumes:
        - application/json
      parameters:
        - name: item
          in: body
          required: true
          description: body containing the following
          type: object
          properties:
            title:
              type: string
              example: thing1
            description:
              type: string
              example: This this a thing
      responses:
        "201":
          description: Status Created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/item"

  /items/{id}:
    get:
      tags: 
          - Items Object
      summary: Get specific item.
      description: Retrieves information for a specific key. If not provided, then the result is root GET request.
      parameters:
        - name: itemKey
          in: path
          required: false
          schema:
            type: string
            format: uuid
          description: Key of object to be retrieved.

    delete:
      tags: 
        - Items Object
      summary: Deletes the item from database
      description: Sends a key to delete from the database.
      parameters:
        - name: itemKey
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: The object to be deleted.



