openapi: 3.0.2
info:
  title: Items API
  description: This is an example API for learning purposes.
  version: 0.0.1

servers:
  - url: http://api.plainrandom.com/
    description: Optional server description, e.g. Main (production) server

paths:
  /items:
    get:
      summary: Returns a list of items.
      description: Returns a list of all Items currently in the database.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string