openapi: 3.0.2
info:
  title: Items API
  description: This is an example API for learning purposes.
  version: 0.0.1

servers:
  # - url: http://localhost:5050/
  - url: https://api.plainrandom.com/
    description: Optional server description, e.g. Main (production) server

components:
  schemas:
    item:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
    items:
      type: array
      additionalProperties:
        $ref: "#/components/schemas/item"


paths:
  /items:
    get:
      summary: Returns a list of items.
      description: Returns a list of all Items currently in the database.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    post:
      summary: Creates an item
      description: Sends a json object to the server and returns with a new entry with new UUID.
      responses:
        "201":
          description: Status Created successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"


